### ISSUE TITLE
[ED]style/structure of descriptions does not match the style of other descriptions

### ISSUE THREAD

**Issue by nrhsinclair** [w3c/wai-selecting-eval-tools#13]
I very much agree with the changes and approve publication. I just noticed the style of the descriptions under these two bullet points are written in fragments, whereas, all of the other descriptions are full sentences:

Automatically Checks
The scope of what the evaluation tool can automatically test. Sometimes a single page. Other times entire groups of related pages. Some can also access password-restricted content.

License
Which licenses the evaluation tool offers, such as Open Source, Commercial, Enterprise, etc.

Suggest revising those descriptions to fit the style of the others:

Automatically Checks
The scope of what the evaluation tool can automatically test varies depending on the tool. Some tools check a single page, while others check entire groups of related pages. Some can also access password-restricted content.

License
Evaluation tools are available under a variety of license types, such as Open Source, Commercial, Enterprise, etc.

**Comment by lakeen** [comment]
Thanks Norah.  I made the changes as suggested.

**Comment by vavroom** [comment]
As @lakeen made the changes, I'm closing this issue.
