### ISSUE TITLE
[!!] Accessibility Information

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-selecting-eval-tools#19]
> Accessibility Information
People with disabilities can and do contribute to the Web. It is important for evaluation tools to be accessible for people with disabilities. Some tools provide information on how well they support accessibility.

First sentence feels not right to me in this context. What about:

> Accessibility Information
It is important that evaluation tools are accessible so that people with disabilities can use them. Some tools provide information on how well they support accessibility.

**Comment by vavroom** [comment]
That first sentence was included to reflect a concept that was in the original text:

> It is equally important to ensure that people with disabilities can effectively contribute to the Web, as it is for them to be able to effectively use the Web.

I'm happy enough to drop the first sentence and use the suggested rewording.
