### ISSUE TITLE
[Introduction] First Bulleted list not needed

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-selecting-eval-tools#2]
In the third paragraph we come across the first bulleted list. This list is a quick list of some of the features of evaluation tools. I understand that this is just an introduction to what will be later on the page, but I think this is not needed in this case as the features are covered very thoroughly in the "Features of Evaluation Tools" section not too far down the page. I would remove that bulleted list altogether.

I think this third paragraph should just be a quick overview of the Tools List  "sister site", including the link to it. And in the paragraph, talk about how this page supports the use of the Tools List database.

**Comment by shawna-slh** [comment]
+1

Since the page itself is fairly simple, the introduction can also be short and simple.

**Comment by lakeen** [comment]
Done.
