### ISSUE TITLE
[ED-LOW] Video transcript grammar fix

### ISSUE THREAD

**Issue by brianelton** [w3c/wai-selecting-eval-tools#34]
**Location** 
Video transcript - https://www.w3.org/WAI/test-evaluate/tools/selecting/

**Current wording**
"A web page and a web site are being scanned fails, passes and interrogations marks are shown."

**Suggested revision**
"A web page and a web site are being scanned; fail, pass, and warning marks are shown."

**Rationale**
Fixing an awkward sentence

**Comment by remibetin** [comment]
Resolved by https://github.com/w3c/wai-selecting-eval-tools/pull/39
