### ISSUE TITLE
[Features of Evaluation Tools] Bullet the list

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-selecting-eval-tools#4]
Under the "Features of Evaluation Tools" section, bullet the list of feature considerations similar to how the "Specific Operations Usages" is bulleted. I think it is easier to scan than having them all be a heading of their own.

Also, up in the opening paragraph of the "Features of Evaluation Tools" maybe mention that most of the features listed below are available by using the "filters" menu on the left side of the List. So when they read through the features list they know that these things can be filtered for, or are described in the search results/tool details.

**Comment by vavroom** [comment]
Thank you Brent, we had originally thought about using a definition list for each feature, but the feedback we'd gotten was that it was better to use headings. Happy to go either way. Just need to make sure everyone is happy with what's done :) 

I'll be adding a paragraph about the filters.

**Comment by shawna-slh** [comment]
/me thought the descriptions were going to be more robust, and thus suggested headings. agree that if they stay so minimal, then <dl> better.

+1 for clearly saying those things are the Filters in the Tools list.

**Comment by vavroom** [comment]
Feedback integrated
