### ISSUE TITLE
[Introduction] Cut Second and Third Bulleted lists, and replace with...

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-selecting-eval-tools#5]
In the [Introduction section](https://github.com/w3c/wai-selecting-eval-tools/blob/master/index.md#introduction) I think the second and third bulleted lists could be removed and this made into one or two sentences. The lists seem to make the page longer than it needs to be. 

Suggest something like this...
> And finally, this document also discusses specific usage of evaluation tools, as well as further aspects to consider when selecting the appropriate tool for a project.

**Comment by lakeen** [comment]
Done.
