### ISSUE TITLE
[ED] Features of Evaluation Tools - more info useful?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-selecting-eval-tools#6]
_ED = Editor's Discretion = please think about, but no need to do big hairy reply if you disagree; you can do brief note and close the issue. :-)_

I imagined that the descriptions under "Features of Evaluation Tools" would be more robust.

For example, would it make sense to move the information from "Specific Operation Usages"
to under "Assists by" ?

Would users benefit from more explanation for some of these Filters? Imagine novices that know  nothing about eval tools...

( @nitedog may have good input on this.)

If the descriptions do stay so short, then I change my mind about them being headings instead of <dl> :-/

**Comment by nitedog** [comment]
Yes, I totally agree with @slhenry - some of these features may need some more explanation for people who are completely new and don't even know what they are looking for.

**Comment by vavroom** [comment]
Neither @lakeen nor I feel there is a pressing need for in depth description. More text may not necessarily be more helpful.
