### ISSUE TITLE
[!!] match Filters

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-selecting-eval-tools#8]
I looked at the Filters in https://www.w3.org/WAI/ER/tools/ :
•	Guidelines
•	Languages
•	Type of tool
•	Technology
•	Assists by …
•	Automatically checks…
•	License

And at the Features of Evaluation Tools in https://github.com/w3c/wai-selecting-eval-tools/blob/master/index.md

I was surprised they don't match.

**Comment by shawna-slh** [comment]
From [Nic 4 Oct e-mail](https://lists.w3.org/Archives/Public/public-eo-plan/2017OctDec/0003.html)

The features of evaluation tools on the github reflect the features listed
under evaluation tools. Some of these features aren't listed with every
tool (I guess it depends on the tool developer submission/information made
available). The filters use a subset of these features.

That might provide the impression that there's a mismatch. There isn't.
It's just that there are more features available than filters available.

**Comment by shawna-slh** [comment]
I think it would be good to make it easier to get info about the filters, and to avoid the impression of mismatch. :-)

Maybe have one section for "Filters" and another for "Other Features" or something like that?

**Comment by vavroom** [comment]
Hey slhenry,

Have you seen the latest update to this? I had actually separated the features into two sections, one that addresses the filterable ones, and the rest. I think that works as you asked for 30 minutes ago, though I pushed these changes last week :)

**Comment by shawna-slh** [comment]
Nope, I hadn't seen the latest update. I guess great minds think alike? ;-)
